### ISSUE TITLE
方便把这个库改成pod方式接入？

### ISSUE THREAD

**Issue by lxhciom** [shaojiankui/JKCategories#13]
我希望长期使用这个库，并且希望通过cocoapods方式，是否可行？

**Comment by shaojiankui** [comment]
我认为Category 不像其他库那样,Category不怎么好控制,还有可以导致些灵异问题,用到哪些拖哪些感觉才是正解

**Comment by dujiepeng** [comment]
这个正解。

**Comment by TheWalkingDead1024** [comment]
为什么我觉得这些Category有的引用了私有API，提交到AppStore会被拒掉。还有一些对界面展示也有影响，我现在已经不敢轻易用这个Category，有哪些违规的我都会注释掉。

**Comment by shaojiankui** [comment]
额...category集合而已,用哪个 自己评估风险使用,再有就是不能一口气全拖进项目啊....那样项目怎么把控

**Comment by larryonline** [comment]
每个 extension 都是独立实现 + prefix 的话我认为可以很大程度上避免另一问题吧. 

ps 我觉得 cocoapods 方式引入项目跟 项目把控没有什么冲突啊.  0 0`

**Comment by shaojiankui** [comment]
done
