### ISSUE TITLE
UINavigationBar致命问题

### ISSUE THREAD

**Issue by devcxm** [shaojiankui/JKCategories#24]
@shaojiankui 使用pod安装后，不添加任何一行分类代码，对UINavigationController的UINavigationBar有致命的UI影响。测试环境：xcode 7.3.1 iOS9.3。

**Comment by shaojiankui** [comment]
上个图

**Comment by devcxm** [comment]
[Test.zip](https://github.com/shaojiankui/JKCategories/files/312139/Test.zip)
你直接运行看效果吧，首先是NavigationBar，再一个你滑动一下UITableVIew，注意看状态栏。

**Comment by Vernsu** [comment]
嗯  之前引入过所有Category，NavigationBar确实有大的问题。
而且部分Category引入了私有API，APP上架的时候有问题。

**Comment by shaojiankui** [comment]
已经修改 1.2 版本已经更新

**Comment by shaojiankui** [comment]
@Vernsu  私有api? 确定?

**Comment by Vernsu** [comment]
@shaojiankui 
看了下版本记录
是这两个文件导致的
UIView+RecursiveDescription.h
UIViewController+RecursiveDescription.h

**Comment by shaojiankui** [comment]
@Vernsu  UIView+RecursiveDescription 我准备删掉 谢谢

**Comment by shaojiankui** [comment]
@Vernsu  1.3已经删掉私有api
