### ISSUE TITLE
下载之后直接报错

### ISSUE THREAD

**Issue by Z-JaDe** [shaojiankui/JKCategories#25]
Use of '@import' when modules are disabled
这个错误我上网上查了一下，说是把enabled modules改成YES就行了，但是我本身就是YES。
然后stackoverflow说是因为我用了ObjectiveC++，所以modules被禁用了，

**Comment by shaojiankui** [comment]
重新更新下1.2

**Comment by shaojiankui** [comment]
1.3 fixed it

**Comment by Z-JaDe** [comment]
另外，我看到uiview中用到了私有方法，需不需要if DEBUG一下？

**Comment by shaojiankui** [comment]
哪个私有方法。。。。。发出来我看看

**Comment by Z-JaDe** [comment]
我去，昨天还在呀，今天找不到了，估计是我看错了，就是这个“recursivedescription”应该是你重写了吧，不过之前有个打印约束的私有方法，现在估计你删掉了。没事的，抱歉了！

**Comment by Z-JaDe** [comment]
我刚才试着更新了一下，最新版还是1.2，是不是需要我手动设置版本？

**Comment by shaojiankui** [comment]
pod update 下
