### ISSUE TITLE
某些方法定义为内联函数比 Category 更合适

### ISSUE THREAD

**Issue by iShawnWang** [shaojiankui/JKCategories#26]
**感谢作者的分享这么丰富的 Category ,666**

比如 `NSObject+JKGCD.m` 类中的 GCD 相关函数
正常使用是

``` Objective-c
[someObject jk_performAsynchronous{
    ...
}];
```

感觉不太合适,下面这样定义为内联函数会不会更好些 ?

``` Objective-c
NS_INLINE void ExecuteAsyncInGlobalQueue(void (^block)()){
    dispatch_async(getGlobalQueue(), block);
};
```

**Comment by shaojiankui** [comment]
合适是合适，但是本库是Category为核心。不会加任何这中函数。牺牲下体验吧。哈哈哈

**Comment by 10YearsDiary** [comment]
这种没必要自定义吧，直接用dispatch_async(getGlobalQueue(), block);不行么。

2016-12-28 10:01 GMT+08:00 Jakey <notifications@github.com>:
