### ISSUE TITLE
Xcode9.0.1     使用pod 'JKCategories' ，使用#import <JKCategories/JKCategories.h>报错：Could not build module 'JKCategories'

### ISSUE THREAD

**Issue by ZYHB** [shaojiankui/JKCategories#36]

**Comment by z234009184** [comment]
是的我也遇到了 只能用 #import "JKCategories.h"  不能用尖括号~~

**Comment by shaojiankui** [comment]
@z234009184  你是不是用的pod 静态库模式啊，不是Framework模式

**Comment by z234009184** [comment]
并不是 用了framework! 别的框架都可以用尖括号  这个就报错找不到 我以为你年久不维护了... 你可以试一下 新建一个空项目 然后 pod 'JKCategories'  直接导入尖括号就会报错...

**Comment by z234009184** [comment]
@shaojiankui

**Comment by shaojiankui** [comment]
把target 下 Build Settings 中 Allow Non-modular includes in Framework Modules 选项卡设为yes。

或者podfile中增加
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      target.build_settings(config.name)['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
`
