### ISSUE TITLE
0分钟前

### ISSUE THREAD

**Issue by l900416** [shaojiankui/JKCategories#37]
文件 **NSDate+JKExtension** 对应 **433** 行，如果当时间小于1分钟时(比如retTime为0.5)，使用该方法会表示为 **0分钟前** ，建议对改行代码进行修正。修正前

```Objective-C
    retTime = retTime <= 0.0 ? 1.0 : retTime;
    return [NSString stringWithFormat:@"%.0f分钟前", retTime];
```

修正后

```Objective-C
    return retTime < 1.0 ? @"刚刚" : [NSString stringWithFormat:@"%.0f分钟前", retTime];
```

**Comment by shaojiankui** [comment]
![qq20171101-154224](https://user-images.githubusercontent.com/5194500/32264830-787991e0-bf1b-11e7-8223-be056f48c4c5.png)
哈哈哈

**Comment by l900416** [comment]
标题很重要！！
