### ISSUE TITLE
UIImageView+JKAddition报错

### ISSUE THREAD

**Issue by 9527kevin** [shaojiankui/JKCategories#39]
![698c91fc-2ce1-4906-b5a9-45c6c98b095a](https://user-images.githubusercontent.com/19398630/34554723-41e922fa-f169-11e7-9ad5-7de629398237.png)
UIImageView+JKAddition 为什么会报这个错呢？根本没问题

**Comment by alexyubin** [comment]
我也出现这个情况, 
你解决了没有?

**Comment by shaojiankui** [comment]
试试1.7 抱错么
