### ISSUE TITLE
UITextView的两个分类，由于重写了deallco方法，会在8.x系统中崩溃

### ISSUE THREAD

**Issue by zhang28602** [shaojiankui/JKCategories#40]
A页面包含TextView 进入A页面后，点击TextView唤起键盘，退出A页面，再次进入，点击TextView会崩溃
stackoverflow上有类似问题
https://stackoverflow.com/questions/35715601/uitextfield-textinputview-message-sent-to-deallocated-instance

**Comment by shaojiankui** [comment]
系统版本？

**Comment by zhang28602** [comment]
8系统都会

**Comment by shaojiankui** [comment]
https://github.com/shaojiankui/JKCategories/commit/4253e25c8195205078eaeb3d592b172b3eb8358b 
我没有测试机，尝试修复了下，能帮忙测下么
