### ISSUE TITLE
UINavigationItem (JKMargin) hook rightItems 有问题

### ISSUE THREAD

**Issue by Akateason** [shaojiankui/JKCategories#41]
UINavigationItem (JKMargin) hook rightItems 有问题. storyboard添加的item全部不显示.

**Comment by ijunfly** [comment]
+1   是的，IB添加的 都没有了，只能手动添加， 赶紧抢救

**Comment by zhoujinhuaxm139com** [comment]
+1 添加的 都没有了，只能手动添加， 赶紧抢救.添加第三方库，背锅，很气。

**Comment by shaojiankui** [comment]
惨痛的教训告诉我们，hook原生控件就是二逼，什么navigation啊 什么tabbar啊。。。统统都是埋雷。。等我一会全给删了

**Comment by shaojiankui** [comment]
1.8.1 移除了这个category
