### ISSUE TITLE
CommonCrypto 是不是有冲突啊

### ISSUE THREAD

**Issue by lijiee** [shaojiankui/JKCategories#49]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/usr/include/CommonCrypto/module.modulemap:1:8: Redefinition of module 'CommonCrypto'

**Comment by lijiee** [comment]
framework module JKCategories {
    umbrella header "JKCategories.h"
    
    export *
    module * { export * }
}
我的解决方法是这个，你看看是否需要修复

**Comment by gitKun** [comment]
同样的问题 xcode 10 报错：
1. Previously defined here 
2. Redefinition of module 'CommonCrypto'

作者应该参考 https://github.com/socketio/socket.io-client-swift/issues/754
修复此问题

**Comment by shaojiankui** [comment]
哎。。增加这个modulemap是为了解决xcode9的Missing required modules CommonCrypto问题，Xcode10应该被官方修复了

**Comment by trusbe** [comment]
天狐辛苦了！

**Comment by w258958134** [comment]
求解决

**Comment by shaojiankui** [comment]
谁给我发一个100%能重现的demo工程。。。

**Comment by shaojiankui** [comment]
知道了。。podfile使用use_frameworks会重现

**Comment by trusbe** [comment]
`module CommonCrypto [system] {
    header "/usr/include/CommonCrypto/CommonCrypto.h"
    export *
}

framework module JKCategories {
}
`
屏蔽项目中这段代码即可。

**Comment by trusbe** [comment]
> @trusbe 是直接注释掉吗，修改的话重新build会复原。现在把xcode10删了，又下回9了

注释掉就可以了。

**Comment by shaojiankui** [comment]
等我push一个1.7.1版本，会把modulemap删掉。
xcode9用1.7版本。xcode10用1.71以后版本。
