### ISSUE TITLE
pod 引入报错，CommonCrypto/CommonCryptor.h找不到，xcode9

### ISSUE THREAD

**Issue by IOSLZZ** [shaojiankui/JKCategories#51]

**Comment by shaojiankui** [comment]
Xcode9使用1.7及之前版本

**Comment by shaojiankui** [comment]
Xcode9使用1.7及之前版本

**Comment by IOSLZZ** [comment]
1.7版本pod找不到发自网易邮箱大师
            在2018年10月12日 18:17，skyfox 写道:Xcode9使用1.7及之前版本

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shaojiankui/JKCategories","title":"shaojiankui/JKCategories","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/shaojiankui/JKCategories"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shaojiankui in #51: Xcode9使用1.7及之前版本"}],"action":{"name":"View Issue","url":"https://github.com/shaojiankui/JKCategories/issues/51#issuecomment-429277911"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shaojiankui/JKCategories/issues/51#issuecomment-429277911",
"url": "https://github.com/shaojiankui/JKCategories/issues/51#issuecomment-429277911",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [shaojiankui/JKCategories] pod 引入报错，CommonCrypto/CommonCryptor.h找不到，xcode9 (#51)",
"sections": [
{
"text": "",
"activityTitle": "**skyfox**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@shaojiankui",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"shaojiankui/JKCategories\",\n\"issueId\": 51,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/shaojiankui/JKCategories/issues/51#issuecomment-429277911"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 392474739\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by shaojiankui** [comment]
不能啊。。我没删啊

**Comment by shaojiankui** [comment]
pod 'JKCategories', '<= 1.7'
