### ISSUE TITLE
UIButton+JKCountDown

### ISSUE THREAD

**Issue by diidiid** [shaojiankui/JKCategories#54]
https://github.com/shaojiankui/JKCategories/blob/a084132f76499c697aebac475e79fc9172d95f3a/JKCategories/UIKit/UIButton/UIButton%2BJKCountDown.m#L26-L36

起始时间为60的时候，按钮因为%60为0而显示不了“60”的状态
（还有命名为“tittle”的问题）

**Comment by shaojiankui** [comment]
用我这个倒计时库吧 ，比较完善。https://github.com/shaojiankui/JKCountDownButton
这个category我稍后修复下。
