### ISSUE TITLE
身份证号精准验证出现偏差

### ISSUE THREAD

**Issue by jifengchao** [shaojiankui/JKCategories#55]
使用了NSString+JKNormalRegex.h中的-jk_accurateVerifyIDCardNumber方法，在验证"152325200207126511"时，显示验证失败。

**Comment by shaojiankui** [comment]
^[1-9][0-9]{5}(19|20)[0-9]{2}((01|03|05|07|08|10|12)(0[1-9]|[1-2][0-9]|3[0-1])|(04|06|09|11)(0[1-9]|[1-2][0-9]|30)|02(0[1-9]|1[0-9]|2[0-8]))[0-9]{3}[0-9Xx]$

嗯，正则 第四个条件应该是 (19|20)。否则2000以后出生的不能校验。
