### ISSUE TITLE
直接下载的项目和pod最新的不一致

### ISSUE THREAD

**Issue by AiBoyuan** [shaojiankui/JKCategories#59]
下载最新的1.8.1版本和pod不一致，比如UIDevice+Hardware这个分类中的+ (NSString *)jk_platformString 方法，下载的有iPhone 11、iPhone 11 Pro和iPhone 11 Pro Max，而pod却没有还停留iPhone XR，希望跟新一下。

**Comment by shaojiankui** [comment]
哎。。。我这破pod不太好用。一直没发布

**Comment by shaojiankui** [comment]
1.8.2
