### ISSUE TITLE
NSDate+JKZeroDate的对象方法中返回的date毫秒不为零

### ISSUE THREAD

**Issue by AiweiChujian** [shaojiankui/JKCategories#69]
\- (NSDate *)jk_zeroDate;
\- (NSDate *)jk_zero24Date;
这两个方法返回的date毫秒不为零，有时会导致基于这两个方法所做的判断不正确，希望在后续版本中将毫秒nanosecond也设置为0再返回

**Comment by shaojiankui** [comment]
ok
