### ISSUE TITLE
请更新UIDevice+JKHardware中的jk_platformString，因为新增了iPhone12系列型号

### ISSUE THREAD

**Issue by lilong7676** [shaojiankui/JKCategories#75]
参考自：https://gist.github.com/adamawolf/3048717

iPhone12,8 : iPhone SE 2nd Gen
iPhone13,1 : iPhone 12 Mini
iPhone13,2 : iPhone 12
iPhone13,3 : iPhone 12 Pro
iPhone13,4 : iPhone 12 Pro Max

**Comment by shaojiankui** [comment]
1.9.2
